[theme]
primaryColor="#FF4B4B"        # A vibrant red for primary elements (buttons, links)
backgroundColor="#F6F8FA"     # White background
secondaryBackgroundColor="#FFFFFF" # White background to match main background for seamless embeds
textColor="#262726"           # Dark text
font="sans serif"